services:
  resumemk:
    build: .
    ports:
      - "10000:10000"
    environment:
      - RUST_LOG=info
    deploy:
      resources:
        limits:
          cpus: "1.0" # Limit the container to 1 CPU
          memory: "2G" # Limit the container to 2GB of RAM
        reservations:
          cpus: "0.5" # Reserve 0.5 CPU
          memory: "1G" # Reserve 1GB of RAM
